theme: jekyll-theme-minimal
title: Nikita Moghe
description: MS by Research Student (CSE) IIT Madras
logo: /assets/logo/nikita.jpg
minima:
  social_links:
    twitter: jekyllrb
    github:  jekyll
    rss: rss

